(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-auto-show-menu 0.3)
 '(ac-comphist-file "~/.emacs.d/data/ac-comphist.dat")
 '(ac-disable-faces nil)
 '(ac-modes
   (quote
    (elixir-mode erlang-mode emacs-lisp-mode lisp-interaction-mode c-mode cc-mode c++-mode java-mode clojure-mode scala-mode scheme-mode coffee-mode ocaml-mode tuareg-mode perl-mode cperl-mode python-mode ruby-mode ecmascript-mode livescript-mode javascript-mode js-mode js2-mode php-mode css-mode makefile-mode sh-mode fortran-mode f90-mode ada-mode xml-mode sgml-mode racket-mode geiser-repl-mode elixir-mode2 lisp-mode slime-repl-mode scala-mode txr-mode)))
 '(ac-quick-help-delay 0.4)
 '(ac-quick-help-prefer-pos-tip t)
 '(ag-highlight-search t)
 '(ag-reuse-buffers t)
 '(auto-indent-backward-delete-char-behavior (quote untabify))
 '(auto-indent-blank-lines-on-move nil)
 '(auto-mark-ignore-move-on-sameline nil)
 '(auto-revert-interval 2)
 '(auto-revert-mode-text " AR")
 '(auto-revert-verbose nil)
 '(auto-save-visited-file-name nil)
 '(blink-cursor-mode nil)
 '(bmkp-last-as-first-bookmark-file "~/.emacs.d/bookmarks")
 '(bookmark-default-file "~/.emacs.d/data/bookmarks")
 '(browse-url-browser-function (quote browse-url-default-macosx-browser))
 '(calendar-date-style (quote european))
 '(calendar-week-start-day 1)
 '(cider-inspector-page-size 50)
 '(cider-pprint-fn (quote pprint))
 '(cider-preferred-build-tool "lein")
 '(cider-prompt-for-symbol nil)
 '(cider-repl-use-pretty-printing t)
 '(coffee-tab-width 4)
 '(column-number-mode t)
 '(company-backends
   (quote
    (company-files
     (company-capf :with company-dabbrev company-dabbrev-code company-keywords company-yasnippet))))
 '(company-dabbrev-code-everywhere t)
 '(company-dabbrev-downcase nil)
 '(company-dabbrev-ignore-case nil)
 '(company-idle-delay t)
 '(company-minimum-prefix-length 2)
 '(company-transformers (quote (company-sort-by-backend-importance)))
 '(completion-ignored-extensions
   (quote
    (".o" "~" ".bin" ".lbin" ".so" ".a" ".ln" ".blg" ".bbl" ".elc" ".lof" ".glo" ".idx" ".lot" ".svn/" ".hg/" ".git/" ".bzr/" "CVS/" "_darcs/" "_MTN/" ".fmt" ".tfm" ".class" ".fas" ".lib" ".mem" ".x86f" ".sparcf" ".dfsl" ".pfsl" ".d64fsl" ".p64fsl" ".lx64fsl" ".lx32fsl" ".dx64fsl" ".dx32fsl" ".fx64fsl" ".fx32fsl" ".sx64fsl" ".sx32fsl" ".wx64fsl" ".wx32fsl" ".fasl" ".ufsl" ".fsl" ".dxl" ".lo" ".la" ".gmo" ".mo" ".toc" ".aux" ".cp" ".fn" ".ky" ".pg" ".tp" ".vr" ".cps" ".fns" ".kys" ".pgs" ".tps" ".vrs" ".pyc" ".pyo")))
 '(css-indent-offset 4)
 '(debug-on-error nil)
 '(debug-on-quit nil)
 '(delete-selection-mode nil)
 '(dired-omit-files "^\\.?#\\|^\\.$\\|^\\.\\.$\\|^\\..+$")
 '(dired-use-ls-dired (quote unspecified))
 '(diredp-hide-details-initially-flag nil)
 '(direx:closed-icon "▶ ")
 '(direx:leaf-icon "- ")
 '(direx:open-icon "▼ ")
 '(dylan-continuation-indent 4)
 '(dylan-indent 4)
 '(ecb-auto-activate t)
 '(ecb-layout-name "left3")
 '(ecb-maximize-ecb-window-after-selection nil)
 '(ecb-options-version "2.40")
 '(ecb-process-non-semantic-files t)
 '(ecb-tip-of-the-day nil)
 '(ecb-use-speedbar-instead-native-tree-buffer nil)
 '(ecb-vc-enable-support t)
 '(ecb-windows-width 0.13)
 '(ede-project-directories (quote ("~/.emacs.d/config")))
 '(ediff-keep-variants nil)
 '(ediff-make-buffers-readonly-at-startup nil)
 '(ediff-merge-split-window-function (quote split-window-horizontally))
 '(ediff-no-emacs-help-in-control-buffer t)
 '(ediff-split-window-function (quote split-window-horizontally))
 '(eldoc-idle-delay 0.2)
 '(elpy-default-minor-modes
   (quote
    (eldoc-mode flymake-mode yas-minor-mode auto-complete-mode)))
 '(elpy-modules
   (quote
    (elpy-module-eldoc elpy-module-flymake elpy-module-pyvenv elpy-module-yasnippet elpy-module-sane-defaults)))
 '(elpy-rpc-backend "jedi")
 '(elpy-rpc-python-command "python")
 '(elscreen-default-buffer-name "*scratch*")
 '(elscreen-tab-display-kill-screen nil)
 '(enable-recursive-minibuffers t)
 '(epg-gpg-program "gpg")
 '(eshell-cannot-leave-input-list
   (quote
    (beginning-of-line-text beginning-of-line move-to-column move-to-left-margin move-to-tab-stop forward-char backward-char delete-char delete-backward-char backward-delete-char backward-delete-char-untabify kill-paragraph backward-kill-paragraph kill-sentence backward-kill-sentence kill-sexp backward-kill-sexp kill-word backward-kill-word kill-region forward-list backward-list forward-page backward-page forward-point forward-paragraph backward-paragraph backward-prefix-chars forward-sentence backward-sentence forward-sexp backward-sexp forward-to-indentation backward-to-indentation backward-up-list forward-word backward-word next-line forward-visible-line forward-comment forward-thing)))
 '(eval-expression-print-length nil)
 '(expand-region-guess-python-mode t)
 '(fast-but-imprecise-scrolling t)
 '(fic-highlighted-words (quote ("FIXME" "TODO" "BUG" "REDFLAG" "XXX")))
 '(fill-column 80)
 '(flymake-checkers-checkers
   (quote
    (flymake-checkers-coffee flymake-checkers-emacs-lisp flymake-checkers-php flymake-checkers-python-flake8 flymake-checkers-python-pyflakes flymake-checkers-ruby flymake-checkers-php flymake-checkers-sh flymake-checkers-sh-bash flymake-checkers-sh-zsh flymake-checkers-tex)))
 '(flymake-no-changes-timeout 5)
 '(flymake-start-syntax-check-on-newline t)
 '(fringe-mode (quote (10 . 8)) nil (fringe))
 '(fuzzy-accept-error-rate 0.2)
 '(geiser-mode-auto-p nil)
 '(generic-ignore-files-regexp "[GPS]*[Tt][Aa][Gg][Ss]\\'")
 '(git-commit-mode-hook
   (quote
    (turn-on-auto-fill flyspell-mode my-magit-commit-hook)) t)
 '(git-commit-summary-max-length 76)
 '(global-auto-revert-non-file-buffers t)
 '(global-git-commit-mode t)
 '(global-linum-mode nil)
 '(global-visible-mark-mode-exclude-alist (quote ("*\\.\\**")))
 '(global-visual-line-mode nil)
 '(gnus-article-sort-functions (quote (gnus-article-sort-by-date)))
 '(gnus-asynchronous t)
 '(gnus-group-mode-hook (quote (gnus-agent-mode gnus-topic-mode)))
 '(gnus-summary-same-subject "(same)")
 '(gnus-thread-sort-functions (quote (gnus-thread-sort-by-most-recent-date)))
 '(golden-ratio-exclude-buffer-names (quote (" *MINIMAP*")))
 '(golden-ratio-mode nil)
 '(helm-M-x-always-save-history t)
 '(helm-adaptive-mode t nil (helm-adaptive))
 '(helm-ag-ignore-patterns (quote ("#*")))
 '(helm-ag-insert-at-point (quote sexp))
 '(helm-ag-use-agignore t)
 '(helm-ag-use-grep-ignore-list t)
 '(helm-bookmark-show-location t)
 '(helm-buffer-skip-remote-checking t)
 '(helm-findutils-search-full-path t)
 '(helm-imenu-fuzzy-match t)
 '(help-at-pt-display-when-idle (quote never) nil (help-at-pt))
 '(help-at-pt-timer-delay 3)
 '(ibuffer-default-shrink-to-minimum-size t)
 '(ibuffer-default-sorting-mode (quote filename/process))
 '(ibuffer-deletion-char 215)
 '(ibuffer-deletion-face (quote web-mode-comment-keyword-face))
 '(ibuffer-elide-long-columns t)
 '(ibuffer-expert t)
 '(ibuffer-formats
   (quote
    ((mark modified read-only " "
           (name 28 28 :left :elide)
           " "
           (size 9 -1 :right)
           " "
           (mode 16 16 :left :elide)
           " " filename-and-process)
     (mark " "
           (name 16 -1)
           " " filename))))
 '(ibuffer-jump-offer-only-visible-buffers t)
 '(ibuffer-load-hook nil)
 '(ibuffer-mode-hook (quote (my-ibuffer-mode-hook)))
 '(ibuffer-old-time 2)
 '(ibuffer-view-ibuffer t)
 '(icicle-Completions-max-columns 1)
 '(icicle-Completions-text-scale-decrease 0.0)
 '(icicle-files-ido-like-flag t)
 '(icicle-mode t)
 '(icicle-show-Completions-initially-flag nil)
 '(ido-create-new-buffer (quote always))
 '(ido-enable-flex-matching t)
 '(ido-save-directory-list-file "~/.emacs.d/data/ido.last")
 '(image-dired-external-viewer "/usr/bin/pinta")
 '(image-dired-thumb-height 250)
 '(image-dired-thumb-size 250)
 '(image-dired-thumb-width 250)
 '(imenu-sort-function (quote imenu--sort-by-name))
 '(imenu-use-popup-menu nil)
 '(indicate-buffer-boundaries nil)
 '(indicate-empty-lines t)
 '(inferior-lisp-program "/bin/sbcl" t)
 '(initial-scratch-message ";; **SCRATCH BUFFER **

")
 '(ivy-display-style (quote fancy))
 '(ivy-height 10)
 '(ivy-wrap t)
 '(jabber-account-list
   (quote
    (("klibertpiotr@10clouds.xmpp.slack.com"
      (:disabled . t)
      (:password . "10clouds.Cixe46iDhcqIeU0hj7SO")
      (:network-server . "10clouds.xmpp.slack.com")
      (:connection-type . starttls))
     ("cji@direct.klibert.pl"
      (:password . "cji")
      (:network-server . "direct.klibert.pl")
      (:connection-type . starttls)))))
 '(jabber-alert-info-message-hooks
   (quote
    (jabber-info-stumpwm jabber-info-beep jabber-info-echo)))
 '(jabber-alert-message-function (quote my-jabber-message-default-message))
 '(jabber-alert-message-hooks
   (quote
    (jabber-message-stumpwm-presence jabber-message-echo jabber-message-scroll)))
 '(jabber-alert-muc-hooks
   (quote
    (jabber-muc-stumpwm jabber-muc-echo jabber-muc-scroll)))
 '(jabber-alert-presence-hooks (quote (jabber-presence-stumpwm-presence)))
 '(jabber-auto-reconnect t)
 '(jabber-backlog-days 300)
 '(jabber-backlog-number 80)
 '(jabber-chat-foreign-prompt-format "[%t] %n>
")
 '(jabber-chat-local-prompt-format "[%t] %n>
")
 '(jabber-connection-ssl-program (quote openssl))
 '(jabber-groupchat-prompt-format "[%t] %n>
")
 '(jabber-history-enabled t)
 '(jabber-invalid-certificate-servers (quote ("klibert.pl" "direct.klibert.pl")))
 '(jabber-reconnect-delay 15)
 '(jedi:complete-on-dot t)
 '(js-indent-level 2)
 '(js2-basic-offset 2)
 '(less-css-indent-level 4)
 '(linum-delay t)
 '(livescript-tab-width 4)
 '(lua-indent-level 4)
 '(lua-indent-string-contents t)
 '(magit-push-always-verify nil)
 '(magit-visit-ref-behavior (quote (create-branch checkout-branch)))
 '(minimap-always-recenter t)
 '(minimap-hide-fringes t)
 '(minimap-highlight-line nil)
 '(minimap-major-modes (quote (prog-mode org-mode)))
 '(minimap-mode t)
 '(minimap-recreate-window nil)
 '(minimap-update-delay 0.3)
 '(mouse-avoidance-threshold 10)
 '(mumamo-background-colors nil)
 '(ns-alternate-modifier (quote super))
 '(ns-auto-hide-menu-bar nil)
 '(ns-command-modifier (quote meta))
 '(nxhtml-menu-mode t)
 '(nxhtml-skip-welcome t)
 '(nxhtml-validation-header-mumamo-modes nil)
 '(org-agenda-files (quote ("~/todo/")))
 '(org-archive-location "todo.archive::datetree/* From %s")
 '(org-babel-js-cmd "/usr/local/bin/node")
 '(org-babel-load-languages
   (quote
    ((emacs-lisp . t)
     (python . t)
     (scheme . t)
     (js . t)
     (io . t)
     (ditaa . t))))
 '(org-babel-process-comment-text (quote org-remove-indentation) nil nil "smc")
 '(org-babel-shell-names
   (quote
    ("sh" "bash" "csh" "ash" "dash" "ksh" "mksh" "posh" "zsh")))
 '(org-babel-tangle-uncomment-comments t)
 '(org-clock-into-drawer t)
 '(org-clock-persist (quote clock))
 '(org-columns-default-format
   "%38ITEM(Details) %6TAGS(Context) %7TODO(To Do) %5Effort(Time){:} %6CLOCKSUM(Total) %16SCHEDULED(Scheduled)")
 '(org-confirm-babel-evaluate nil)
 '(org-default-notes-file "~/todo/notes")
 '(org-directory "~/todo/")
 '(org-drawers (quote ("PROPERTIES" "CLOCK" "LOGBOOK" "RESULTS" "NOTES")))
 '(org-emphasis-alist
   (quote
    (("*" bold "<b>" "</b>")
     ("/" italic "<i>" "</i>")
     ("_" underline "<span style=\"text-decoration:underline;\">" "</span>")
     ("=" org-code "<code>" "</code>" verbatim)
     ("`" org-code "<code>" "</code>" verbatim)
     ("~" org-verbatim "<code>" "</code>" verbatim)
     ("+"
      (:strike-through t)
      "<del>" "</del>"))))
 '(org-enforce-todo-dependencies t)
 '(org-export-coding-system (quote utf-8))
 '(org-export-creator-string "")
 '(org-export-use-babel nil)
 '(org-export-with-statistics-cookies nil)
 '(org-global-properties
   (quote
    (("Effort_ALL" . "0:05 0:15 0:30 1:00 1:30 2:00 4:00 6:00 8:00"))))
 '(org-habit-graph-column 60)
 '(org-habit-show-habits-only-for-today nil)
 '(org-hide-leading-stars t)
 '(org-hierarchical-todo-statistics nil)
 '(org-html-infojs-options
   (quote
    ((path . "http://orgmode.org/org-info.js")
     (view . "info")
     (toc . :with-toc)
     (ftoc . "0")
     (tdepth . "max")
     (sdepth . "max")
     (mouse . "underline")
     (buttons . "0")
     (ltoc . "1")
     (up . :html-link-up)
     (home . :html-link-home))))
 '(org-html-keep-old-src t)
 '(org-html-klipse-js
   "https://storage.googleapis.com/app.klipse.tech/plugin_prod/js/klipse_plugin.min.js")
 '(org-html-klipsify-src nil)
 '(org-log-done (quote note))
 '(org-log-into-drawer t)
 '(org-log-repeat (quote note))
 '(org-modules
   (quote
    (org-bbdb org-bibtex org-docview org-gnus org-id org-info org-eshell org-habit org-inlinetask org-mhe org-rmail org-w3m)))
 '(org-refile-targets
   (quote
    ((nil :maxlevel . 3)
     (org-agenda-files :maxlevel . 1))))
 '(org-show-siblings (quote ((default . t) (isearch t))))
 '(org-special-ctrl-a/e t)
 '(org-special-ctrl-k t)
 '(org-src-fontify-natively t)
 '(org-tag-alist
   (quote
    ((:startgroup)
     ("WORK" . 119)
     ("HOME" . 104)
     ("SIMPLY" . 115)
     ("CASTORAMA" . 99)
     (:endgroup "")
     ("LODZ" . 108)
     ("RABIEN" . 114)
     ("BLOG" . 98)
     ("Michal" . 109))))
 '(org-tags-column -90)
 '(org-todo-keywords
   (quote
    ((sequence "TODO(t!)" "NEXT(n!)" "WAITING(w@)" "|" "DONE(d@)" "CANCELED(c@)")
     (sequence "INACTIVE(i!)" "ACTIVE(a@)" "SUSPENDED(u@)" "|" "FINISHED(f@)"))))
 '(org-use-sub-superscripts nil)
 '(package-archives
   (quote
    (("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa" . "http://melpa.milkbox.net/packages/")
     ("marmalade" . "https://marmalade-repo.org/packages/")
     ("elpy" . "https://jorgenschaefer.github.io/packages/"))))
 '(package-enable-at-startup nil)
 '(package-selected-packages
   (quote
    (with-editor groovy-mode function-args cmake-mode nasm-mode plantuml-mode alpha avy ace-window ac-geiser ac-js2 ac-slime ace-jump-buffer ack ag alchemist auto-complete-nxml auto-indent-mode buffer-stack cider clips-mode clj-mode clojure-mode coffee-mode col-highlight company-inf-python crontab-mode dired+ ein elixir-mode elnode epc epoch-view eshell-manual f fic-ext-mode fill-column-indicator find-file-in-git-repo find-file-in-project flymake-jshint flymake-python-pyflakes fringe-helper fsharp-mode fuzzy ggtags gh git-auto-commit-mode git-commit-mode git-rebase-mode gitconfig-mode haxe-mode highlight highlight-indentation highline hl-line+ hl-sentence hl-sexp hy-mode idle-highlight-mode ido-load-library ido-ubiquitous idomenu iedit ipython iy-go-to-char j-mode jabber jade-mode jira json-mode less-css-mode levenshtein livescript-mode loop macrostep main-line mmm-mode mo-git-blame neotree nginx-mode nose nurumacs occur-default-current-word occur-x outline-magic outlined-elisp-mode paredit-everywhere paredit-menu parenface parenface-plus pcre2el peg pep8 phi-rectangle phi-search-mc project pycomplete pyflakes pylint pymacs python-django python-pylint pyvirtualenv quack rainbow-delimiters rainbow-mode regex-dsl register-list rust-mode scala-mode2 sentence-highlight shampoo shell-here slamhound slime smex sr-speedbar synosaurus tidy tuareg unbound undo-tree virtualenv w3m xml-rpc yaml-mode zencoding-mode)))
 '(powerline-default-separator (quote rounded))
 '(powerline-height nil)
 '(powerline-text-scale-factor nil)
 '(proced-auto-update-flag t)
 '(proced-auto-update-interval 2)
 '(prolog-electric-colon-flag t)
 '(prolog-electric-dot-flag t)
 '(prolog-indent-width 4)
 '(python-check-command "flake8")
 '(python-environment-virtualenv (quote ("virtualenv" "--system-site-packages" "--quiet")))
 '(quack-programs
   (quote
    ("csi -:c" "mzscheme" "bigloo" "csi" "csi -hygienic" "gosh" "gracket" "gsi" "gsi ~~/syntax-case.scm -" "guile" "kawa" "mit-scheme" "racket" "racket -il typed/racket" "rs" "scheme" "scheme48" "scsh" "sisc" "stklos" "sxi")))
 '(racket-racket-program "/Applications/Racket v6.8/bin/racket")
 '(racket-raco-program "/Applications/Racket v6.8/bin/raco")
 '(racket-use-company-mode nil)
 '(recentf-auto-cleanup (quote never))
 '(recentf-max-menu-items 500)
 '(recentf-max-saved-items 1000)
 '(recentf-menu-action (quote find-file))
 '(recentf-save-file "~/.emacs.d/data/recentf")
 '(safe-local-variable-values
   (quote
    ((bug-reference-bug-regexp . "#\\(?2:[0-9]+\\)")
     (cider-cljs-lein-repl . "(do (dev) (go) (cljs-repl))")
     (cider-refresh-after-fn . "reloaded.repl/resume")
     (cider-refresh-before-fn . "reloaded.repl/suspend")
     (checkdoc-package-keywords-flag)
     (bug-reference-bug-regexp . "#\\(?2:[[:digit:]]+\\)")
     (checkdoc-package-keywords-flag)
     (mangle-whitespace . t)
     (Lowercase . Yes)
     (Syntax . Common-lisp)
     (Lowercase . YES)
     (Base . 10)
     (Syntax . COMMON-LISP)
     (Package . XLIB)
     (eval setq org-html-postamble nil)
     (python-shell-completion-string-code . "';'.join(get_ipython().Completer.all_completions('''%s'''))
")
     (python-shell-completion-module-string-code . "';'.join(module_completion('''%s'''))
")
     (python-shell-completion-setup-code . "from IPython.core.completerlib import module_completion")
     (python-shell-interpreter-args . "/usr/www/tagasauris/tagasauris/manage.py shell")
     (python-shell-interpreter . "python")
     (whitespace-line-column . 80))))
 '(scheme-program-name "csi -:c")
 '(scroll-conservatively 108)
 '(semanticdb-project-roots (quote ("/usr/www/tagasauris/")))
 '(set-mark-command-repeat-pop t)
 '(sgml-basic-offset 2)
 '(shell-file-name "/bin/bash")
 '(show-paren-mode t)
 '(slime-repl-history-file "~/.emacs.d/data/slime-history.eld")
 '(slime-repl-history-remove-duplicates t)
 '(slime-repl-history-trim-whitespaces t)
 '(speedbar-default-position (quote left))
 '(speedbar-hide-button-brackets-flag t)
 '(speedbar-show-unknown-files t)
 '(speedbar-tag-regroup-maximum-length 4)
 '(speedbar-verbosity-level 1)
 '(sr-confirm-kill-viewer nil)
 '(sr-speedbar-auto-refresh nil)
 '(sr-speedbar-right-side nil)
 '(sr-use-commander-keys t)
 '(sr-windows-locked nil)
 '(srecode-map-save-file "~/.emacs.d/data/srecode-map.el" t)
 '(starttls-extra-arguments (quote ("--insecure")))
 '(synosaurus-choose-method (quote popup))
 '(tab-stop-list
   (quote
    (4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92 96 100 104 108 112 116 120)))
 '(tags-revert-without-query t)
 '(tool-bar-mode nil)
 '(tramp-backup-directory-alist (quote (("." . "~/.saves"))) nil (tramp))
 '(tramp-verbose 5 nil (tramp))
 '(truncate-lines t)
 '(truncate-partial-width-windows nil)
 '(undo-tree-auto-save-history t)
 '(undo-tree-history-directory-alist (quote (("." . "~/.emacs.d/undo-history"))))
 '(uniquify-buffer-name-style (quote post-forward) nil (uniquify))
 '(uniquify-separator ":")
 '(uniquify-strip-common-suffix t)
 '(uniquify-trailing-separator-p t)
 '(visible-mark-max 3)
 '(visual-line-fringe-indicators (quote (nil nil)))
 '(web-mode-code-indent-offset 4)
 '(web-mode-comment-style 1)
 '(web-mode-css-indent-offset 2)
 '(web-mode-disable-auto-pairing nil)
 '(web-mode-disable-css-colorization t)
 '(web-mode-enable-block-faces nil)
 '(web-mode-enable-current-element-highlight t)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-script-padding 4)
 '(web-mode-style-padding 4)
 '(web-mode-tag-auto-close-style 2))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aw-leading-char-face ((t (:foreground "red" :height 4.0))))
 '(bmkp-local-directory ((t (:foreground "dark orange"))))
 '(bmkp-local-file-without-region ((t (:foreground "cyan"))))
 '(css-selector ((t (:inherit font-lock-function-name-face :foreground "deep sky blue"))))
 '(elscreen-tab-current-screen-face ((t (:background "wheat2" :foreground "black"))))
 '(elscreen-tab-other-screen-face ((t (:background "SkyBlue3" :foreground "black" :underline t))))
 '(font-lock-fic-face ((t (:background "wheat4" :foreground "cyan" :weight bold))))
 '(helm-ff-file ((t (:inherit nil))))
 '(hl-line ((t (:background "gray18"))))
 '(hl-sexp-face ((t (:background "gray23"))))
 '(j-verb-face ((t (:foreground "dark cyan"))))
 '(magit-item-highlight ((t (:background "gray19" :underline nil))))
 '(minimap-active-region-background ((t (:background "gray24"))))
 '(powerline-active1 ((t (:inherit mode-line :background "gray22"))))
 '(powerline-active2 ((t (:inherit mode-line :background "gray40"))))
 '(powerline-inactive1 ((t (:inherit mode-line-inactive :background "gray11"))))
 '(powerline-inactive2 ((t (:inherit mode-line-inactive :background "gray20"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "cadet blue"))))
 '(swiper-line-face ((t (:inherit highlight :background "black"))))
 '(swiper-match-face-1 ((t (:inherit isearch-lazy-highlight-face :background "black"))))
 '(swiper-match-face-2 ((t (:inherit isearch :background "black"))))
 '(swiper-match-face-3 ((t (:inherit match :background "black"))))
 '(table-cell ((t (:background "gray20" :foreground "gray90" :inverse-video nil))))
 '(visible-mark-face ((t (:background "gray26")))))

(toggle-diredp-find-file-reuse-dir 1)

(put 'narrow-to-region 'disabled nil)
(put 'upcase-region    'disabled nil)
(put 'set-goal-column  'disabled nil)
(put 'erase-buffer     'disabled nil)
