;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        backward-sexp
        beginning-of-buffer
        coffee-dedent-line-backspace
        delete-indentation
        elscreen-create
        end-of-buffer
        forward-sexp
        indent-for-tab-command
        kill-region
        kill-sexp
        livescript-dedent-line-backspace
        mark-lines-next-line
        mark-word
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-self-insert-command
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-meta-doublequote
        paredit-open-round
        paredit-wrap-round
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        suspend-frame
        ))

(setq mc/cmds-to-run-once
      '(
        elscreen-next
        iedit-mode
        smex
        ))
