;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning
        backward-sexp
        beginning-of-buffer
        coffee-dedent-line-backspace
        comment-or-uncomment-region-or-line
        delete-indentation
        electric-pair-backward-delete-char
        elscreen-create
        end-of-buffer
        eval-last-sexp
        forward-sexp
        indent-for-tab-command
        iy-go-to-char--command
        kill-region
        kill-sexp
        livescript-dedent-line-backspace
        mark-lines-next-line
        mark-word
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        orgtbl-hijacker-command-3
        orgtbl-self-insert-command
        overwrite-mode
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-meta-doublequote
        paredit-newline
        paredit-open-round
        paredit-wrap-round
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        suspend-frame
        transpose-sexps
        wdired-capitalize-word
        wdired-next-line
        wdired-previous-line
        wdired-upcase-word
        ))

(setq mc/cmds-to-run-once
      '(
        elscreen-next
        iedit-mode
        smex
        ))
