;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-buffer
        elscreen-create
        end-of-buffer
        forward-sexp
        indent-for-tab-command
        kill-sexp
        mark-word
        org-beginning-of-line
        org-end-of-line
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-open-round
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        ))

(setq mc/cmds-to-run-once
      '(
        elscreen-next
        ))
